// Generated by Haxe 3.4.2
package markov.util;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class EditDistanceMetrics extends haxe.lang.HxObject
{
	public EditDistanceMetrics(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public EditDistanceMetrics()
	{
		//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		markov.util.EditDistanceMetrics.__hx_ctor_markov_util_EditDistanceMetrics(this);
	}
	
	
	public static void __hx_ctor_markov_util_EditDistanceMetrics(markov.util.EditDistanceMetrics __hx_this)
	{
	}
	
	
	public static int levenshtein(java.lang.String source, java.lang.String target)
	{
		//line 23 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		if ( ! ((((boolean) (( source != null )) ))) ) 
		{
			//line 23 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: source != null");
		}
		
		//line 24 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		if ( ! ((((boolean) (( target != null )) ))) ) 
		{
			//line 24 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: target != null");
		}
		
		//line 25 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		int slen = source.length();
		//line 26 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		int tlen = target.length();
		//line 28 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		if (( slen == 0 )) 
		{
			//line 29 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			return tlen;
		}
		
		//line 31 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		if (( tlen == 0 )) 
		{
			//line 32 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			return slen;
		}
		
		//line 35 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		int[] this1 = new int[( tlen + 1 )];
		//line 35 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		int[] costs = ((int[]) (this1) );
		//line 36 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		{
			//line 36 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			int _g1 = 0;
			//line 36 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			int _g = ((int[]) (costs) ).length;
			//line 36 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			while (( _g1 < _g ))
			{
				//line 36 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
				int i = _g1++;
				//line 37 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
				((int[]) (costs) )[i] = i;
			}
			
		}
		
		//line 40 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		int s = 0;
		//line 41 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		while (( s < source.length() ))
		{
			//line 42 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			((int[]) (costs) )[0] = ( s + 1 );
			//line 43 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			int corner = s;
			//line 44 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			int t = 0;
			//line 45 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			while (( t < target.length() ))
			{
				//line 46 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
				int upper = ((int) (((int[]) (costs) )[( t + 1 )]) );
				//line 47 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
				if (haxe.lang.Runtime.valEq(haxe.lang.StringExt.charAt(source, s), haxe.lang.StringExt.charAt(target, t))) 
				{
					//line 48 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
					((int[]) (costs) )[( t + 1 )] = corner;
				}
				else
				{
					//line 50 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
					int tc = ( (( upper < corner )) ? (upper) : (corner) );
					//line 51 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
					((int[]) (costs) )[( t + 1 )] = ( (( (( ((int) (((int[]) (costs) )[t]) ) < tc )) ? (((int) (((int[]) (costs) )[t]) )) : (tc) )) + 1 );
				}
				
				//line 53 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
				corner = upper;
				//line 54 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
				 ++ t;
			}
			
			//line 56 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			 ++ s;
		}
		
		//line 59 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		return ((int[]) (costs) )[( ((int[]) (costs) ).length - 1 )];
	}
	
	
	public static int damerauLevenshtein(java.lang.String source, java.lang.String target)
	{
		//line 72 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		if ( ! ((((boolean) (( source != null )) ))) ) 
		{
			//line 72 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: source != null");
		}
		
		//line 73 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		if ( ! ((((boolean) (( target != null )) ))) ) 
		{
			//line 73 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: target != null");
		}
		
		//line 75 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		if (( source.length() == 0 )) 
		{
			//line 76 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			return target.length();
		}
		
		//line 78 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		if (( target.length() == 0 )) 
		{
			//line 79 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			return source.length();
		}
		
		//line 81 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		int[] table = markov.util.EditDistanceMetrics.damerauLevenshteinMatrix(source, target, true);
		//line 82 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		return ((int[]) (table) )[( ((int[]) (table) ).length - 1 )];
	}
	
	
	public static int[] damerauLevenshteinMatrix(java.lang.String source, java.lang.String target, java.lang.Object enableTranspositions)
	{
		//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		boolean __temp_enableTranspositions2 = ( (haxe.lang.Runtime.eq(enableTranspositions, null)) ? (true) : (haxe.lang.Runtime.toBool(enableTranspositions)) );
		//line 94 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		if ( ! ((((boolean) (( ( source != null ) && ( target != null ) )) ))) ) 
		{
			//line 94 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: source != null && target != null");
		}
		
		//line 95 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		int w = source.length();
		//line 96 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		int h = target.length();
		//line 98 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		if (( ( w == 0 ) || ( h == 0 ) )) 
		{
			//line 99 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			int[] this1 = new int[0];
			//line 99 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			return ((int[]) (this1) );
		}
		
		//line 102 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		 ++ w;
		//line 103 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		 ++ h;
		//line 104 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		int[] this2 = new int[( w * h )];
		//line 104 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		int[] costs = ((int[]) (this2) );
		//line 105 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		{
			//line 105 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			int _g1 = 0;
			//line 105 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			int _g = w;
			//line 105 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			while (( _g1 < _g ))
			{
				//line 105 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
				int i = _g1++;
				//line 106 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
				((int[]) (costs) )[i] = i;
			}
			
		}
		
		//line 108 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		{
			//line 108 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			int _g11 = 1;
			//line 108 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			int _g2 = h;
			//line 108 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			while (( _g11 < _g2 ))
			{
				//line 108 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
				int j = _g11++;
				//line 109 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
				((int[]) (costs) )[( j * w )] = j;
			}
			
		}
		
		//line 112 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		int cost = 0;
		//line 113 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		{
			//line 113 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			int _g12 = 1;
			//line 113 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			int _g3 = w;
			//line 113 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
			while (( _g12 < _g3 ))
			{
				//line 113 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
				int x = _g12++;
				//line 114 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
				{
					//line 114 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
					int _g31 = 1;
					//line 114 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
					int _g21 = h;
					//line 114 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
					while (( _g31 < _g21 ))
					{
						//line 114 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
						int y = _g31++;
						//line 115 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
						if (haxe.lang.Runtime.valEq(haxe.lang.StringExt.charAt(source, ( x - 1 )), haxe.lang.StringExt.charAt(target, ( y - 1 )))) 
						{
							//line 116 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
							cost = 0;
						}
						else
						{
							//line 118 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
							cost = 1;
						}
						
						//line 121 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
						int a = ( ((int) (((int[]) (costs) )[( ( x - 1 ) + ( y * w ) )]) ) + 1 );
						//line 122 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
						int a1 = ( ((int) (((int[]) (costs) )[( x + ( (( y - 1 )) * w ) )]) ) + 1 );
						//line 122 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
						int b = ( ((int) (((int[]) (costs) )[( ( x - 1 ) + ( (( y - 1 )) * w ) )]) ) + cost );
						//line 121 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
						int b1 = ( (( a1 < b )) ? (a1) : (b) );
						//line 121 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
						((int[]) (costs) )[( x + ( y * w ) )] = ( (( a < b1 )) ? (a) : (b1) );
						//line 125 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
						if (( ( ( ( __temp_enableTranspositions2 && ( x > 1 ) ) && ( y > 1 ) ) && haxe.lang.Runtime.valEq(haxe.lang.StringExt.charAt(source, x), haxe.lang.StringExt.charAt(target, ( y - 1 ))) ) && haxe.lang.Runtime.valEq(haxe.lang.StringExt.charAt(source, ( x - 1 )), haxe.lang.StringExt.charAt(target, y)) )) 
						{
							//line 126 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
							int a2 = ((int) (((int[]) (costs) )[( x + ( y * w ) )]) );
							//line 126 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
							int b2 = ( ((int) (((int[]) (costs) )[( ( x - 2 ) + ( (( y - 2 )) * w ) )]) ) + cost );
							//line 126 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
							((int[]) (costs) )[( x + ( y * w ) )] = ( (( a2 < b2 )) ? (a2) : (b2) );
						}
						
					}
					
				}
				
			}
			
		}
		
		//line 131 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/EditDistanceMetrics.hx"
		return costs;
	}
	
	
}


