// Generated by Haxe 3.4.2
package markov.util;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class FileReader extends haxe.lang.HxObject
{
	public FileReader(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public FileReader()
	{
		//line 16 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/FileReader.hx"
		markov.util.FileReader.__hx_ctor_markov_util_FileReader(this);
	}
	
	
	public static void __hx_ctor_markov_util_FileReader(markov.util.FileReader __hx_this)
	{
	}
	
	
}


