// Generated by Haxe 3.4.2
package markov.namegen;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Generator extends haxe.lang.HxObject
{
	public Generator(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Generator(haxe.root.Array<java.lang.String> data, int order, double prior)
	{
		//line 45 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		markov.namegen.Generator.__hx_ctor_markov_namegen_Generator(this, data, order, prior);
	}
	
	
	public static void __hx_ctor_markov_namegen_Generator(markov.namegen.Generator __hx_this, haxe.root.Array<java.lang.String> data, int order, double prior)
	{
		//line 46 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		if ( ! ((((boolean) (( data != null )) ))) ) 
		{
			//line 46 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: data != null");
		}
		
		//line 47 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		boolean aNeg = ( ((int) (order) ) < 0 );
		//line 47 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		boolean bNeg = ( ((int) (1) ) < 0 );
		//line 47 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		if ( ! ((((boolean) (( (( aNeg != bNeg )) ? (aNeg) : (( ((int) (order) ) >= ((int) (1) ) )) )) ))) ) 
		{
			//line 47 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: order >= 1");
		}
		
		//line 48 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		if ( ! ((((boolean) (( prior >= 0 )) ))) ) 
		{
			//line 48 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: prior >= 0");
		}
		
		//line 50 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		__hx_this.order = order;
		//line 51 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		__hx_this.prior = prior;
		//line 54 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		haxe.root.Array<java.lang.String> letters = ((haxe.root.Array<java.lang.String>) (markov.util._ArraySet.ArraySet_Impl_.create(((haxe.root.Array<java.lang.String>) (null) ))) );
		//line 55 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		{
			//line 55 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			int _g = 0;
			//line 55 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			while (( _g < data.length ))
			{
				//line 55 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				java.lang.String word = data.__get(_g);
				//line 55 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				 ++ _g;
				//line 56 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				{
					//line 56 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					int _g2 = 0;
					//line 56 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					int _g1 = word.length();
					//line 56 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					while (( _g2 < _g1 ))
					{
						//line 56 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						int i = _g2++;
						//line 57 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						markov.util._ArraySet.ArraySet_Impl_.add(((haxe.root.Array<java.lang.String>) (letters) ), haxe.lang.Runtime.toString(haxe.lang.StringExt.charAt(word, i)));
					}
					
				}
				
			}
			
		}
		
		//line 60 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		letters.sort(( (( markov.namegen.Generator___hx_ctor_markov_namegen_Generator_60__Fun.__hx_current != null )) ? (markov.namegen.Generator___hx_ctor_markov_namegen_Generator_60__Fun.__hx_current) : (markov.namegen.Generator___hx_ctor_markov_namegen_Generator_60__Fun.__hx_current = ((markov.namegen.Generator___hx_ctor_markov_namegen_Generator_60__Fun) (new markov.namegen.Generator___hx_ctor_markov_namegen_Generator_60__Fun()) )) ));
		//line 69 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		haxe.root.Array<java.lang.String> domain = ((haxe.root.Array<java.lang.String>) (markov.util._ArraySet.ArraySet_Impl_.toArray(((haxe.root.Array<java.lang.String>) (letters) ))) );
		//line 70 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		domain.insert(0, "#");
		//line 73 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		__hx_this.models = new haxe.root.Array<markov.namegen.Model>();
		//line 74 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		{
			//line 74 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			int _g11 = 0;
			//line 74 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			int _g3 = ((int) (order) );
			//line 74 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			while (( _g11 < _g3 ))
			{
				//line 74 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				int i1 = _g11++;
				//line 75 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				__hx_this.models.push(new markov.namegen.Model(data.copy(), ((int) (( ((int) (order) ) - ((int) (i1) ) )) ), prior, domain));
			}
			
		}
		
	}
	
	
	public int order;
	
	public double prior;
	
	public haxe.root.Array<markov.namegen.Model> models;
	
	public java.lang.String generate()
	{
		//line 84 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		int times = this.order;
		//line 84 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		if ( ! (((boolean) (true) )) ) 
		{
			//line 84 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: str != null");
		}
		
		//line 84 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		if ( ! ((((boolean) (( times >= 1 )) ))) ) 
		{
			//line 84 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: times >= 1");
		}
		
		//line 84 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		java.lang.String output = "";
		//line 84 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		{
			//line 84 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			int _g1 = 0;
			//line 84 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			int _g = times;
			//line 84 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			while (( _g1 < _g ))
			{
				//line 84 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				int i = _g1++;
				//line 84 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				output += "#";
			}
			
		}
		
		//line 84 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		java.lang.String word = output;
		//line 85 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		java.lang.String letter = this.getLetter(word);
		//line 86 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		while ( ! (haxe.lang.Runtime.valEq(letter, "#")) )
		{
			//line 87 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			if (( letter != null )) 
			{
				//line 88 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				word += letter;
			}
			
			//line 90 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			letter = this.getLetter(word);
		}
		
		//line 92 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		return word;
	}
	
	
	public java.lang.String getLetter(java.lang.String context)
	{
		//line 101 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		if ( ! ((((boolean) (( context != null )) ))) ) 
		{
			//line 101 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: context != null");
		}
		
		//line 102 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		if ( ! ((((boolean) (( context.length() > 0 )) ))) ) 
		{
			//line 102 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: context.length > 0");
		}
		
		//line 104 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		java.lang.String letter = null;
		//line 105 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		java.lang.String context1 = haxe.lang.StringExt.substring(context, ((int) (( ((int) (context.length()) ) - ((int) (this.order) ) )) ), context.length());
		//line 106 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		{
			//line 106 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			int _g = 0;
			//line 106 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			haxe.root.Array<markov.namegen.Model> _g1 = this.models;
			//line 106 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			while (( _g < _g1.length ))
			{
				//line 106 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				markov.namegen.Model model = _g1.__get(_g);
				//line 106 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				 ++ _g;
				//line 107 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				letter = model.generate(context1);
				//line 108 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				if (( letter == null )) 
				{
					//line 109 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					context1 = haxe.lang.StringExt.substring(context1, 1, null);
				}
				else
				{
					//line 111 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
			}
			
		}
		
		//line 114 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		return letter;
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		{
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			boolean __temp_executeDef1 = true;
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			switch (field.hashCode())
			{
				case 106934986:
				{
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					if (field.equals("prior")) 
					{
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						__temp_executeDef1 = false;
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						this.prior = ((double) (value) );
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						return value;
					}
					
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
				
				case 106006350:
				{
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					if (field.equals("order")) 
					{
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						__temp_executeDef1 = false;
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						this.order = ((int) (value) );
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						return value;
					}
					
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
				
			}
			
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			if (__temp_executeDef1) 
			{
				//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		{
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			boolean __temp_executeDef1 = true;
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			switch (field.hashCode())
			{
				case -1068799382:
				{
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					if (field.equals("models")) 
					{
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						__temp_executeDef1 = false;
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						this.models = ((haxe.root.Array<markov.namegen.Model>) (value) );
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						return value;
					}
					
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
				
				case 106006350:
				{
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					if (field.equals("order")) 
					{
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						__temp_executeDef1 = false;
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						this.order = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						return value;
					}
					
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
				
				case 106934986:
				{
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					if (field.equals("prior")) 
					{
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						__temp_executeDef1 = false;
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						this.prior = ((double) (haxe.lang.Runtime.toDouble(value)) );
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						return value;
					}
					
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
				
			}
			
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			if (__temp_executeDef1) 
			{
				//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		{
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			boolean __temp_executeDef1 = true;
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			switch (field.hashCode())
			{
				case 589842204:
				{
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					if (field.equals("getLetter")) 
					{
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						__temp_executeDef1 = false;
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "getLetter")) );
					}
					
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
				
				case 106006350:
				{
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					if (field.equals("order")) 
					{
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						__temp_executeDef1 = false;
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						return this.order;
					}
					
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
				
				case 1810371957:
				{
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					if (field.equals("generate")) 
					{
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						__temp_executeDef1 = false;
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "generate")) );
					}
					
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
				
				case 106934986:
				{
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					if (field.equals("prior")) 
					{
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						__temp_executeDef1 = false;
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						return this.prior;
					}
					
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
				
				case -1068799382:
				{
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					if (field.equals("models")) 
					{
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						__temp_executeDef1 = false;
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						return this.models;
					}
					
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
				
			}
			
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			if (__temp_executeDef1) 
			{
				//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		{
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			boolean __temp_executeDef1 = true;
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			switch (field.hashCode())
			{
				case 106934986:
				{
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					if (field.equals("prior")) 
					{
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						__temp_executeDef1 = false;
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						return this.prior;
					}
					
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
				
				case 106006350:
				{
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					if (field.equals("order")) 
					{
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						__temp_executeDef1 = false;
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						return ((double) (this.order) );
					}
					
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
				
			}
			
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			if (__temp_executeDef1) 
			{
				//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		{
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			boolean __temp_executeDef1 = true;
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			switch (field.hashCode())
			{
				case 589842204:
				{
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					if (field.equals("getLetter")) 
					{
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						__temp_executeDef1 = false;
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						return this.getLetter(haxe.lang.Runtime.toString(dynargs.__get(0)));
					}
					
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
				
				case 1810371957:
				{
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					if (field.equals("generate")) 
					{
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						__temp_executeDef1 = false;
						//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
						return this.generate();
					}
					
					//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
					break;
				}
				
				
			}
			
			//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
			if (__temp_executeDef1) 
			{
				//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		baseArr.push("models");
		//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		baseArr.push("prior");
		//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		baseArr.push("order");
		//line 18 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Generator.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


