// Generated by Haxe 3.4.2
package markov.namegen;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Model extends haxe.lang.HxObject
{
	public Model(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Model(haxe.root.Array<java.lang.String> data, int order, double prior, haxe.root.Array<java.lang.String> alphabet)
	{
		//line 43 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		markov.namegen.Model.__hx_ctor_markov_namegen_Model(this, data, order, prior, alphabet);
	}
	
	
	public static void __hx_ctor_markov_namegen_Model(markov.namegen.Model __hx_this, haxe.root.Array<java.lang.String> data, int order, double prior, haxe.root.Array<java.lang.String> alphabet)
	{
		//line 44 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		if ( ! ((((boolean) (( ( alphabet != null ) && ( data != null ) )) ))) ) 
		{
			//line 44 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: alphabet != null && data != null");
		}
		
		//line 45 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		if ( ! ((((boolean) (( ( alphabet.length > 0 ) && ( data.length > 0 ) )) ))) ) 
		{
			//line 45 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: alphabet.length > 0 && data.length > 0");
		}
		
		//line 46 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		if ( ! ((((boolean) (( ( prior >= 0 ) && ( prior <= 1 ) )) ))) ) 
		{
			//line 46 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: prior >= 0 && prior <= 1");
		}
		
		//line 48 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		__hx_this.order = order;
		//line 49 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		__hx_this.prior = prior;
		//line 50 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		__hx_this.alphabet = alphabet;
		//line 52 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		__hx_this.observations = new haxe.ds.StringMap<haxe.root.Array<java.lang.String>>();
		//line 53 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		__hx_this.train(data);
		//line 54 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		__hx_this.buildChains();
	}
	
	
	public static int countMatches(haxe.root.Array<java.lang.String> arr, java.lang.String v)
	{
		//line 132 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		if (( arr == null )) 
		{
			//line 133 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			return 0;
		}
		
		//line 136 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		int i = 0;
		//line 137 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		{
			//line 137 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			int _g = 0;
			//line 137 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			while (( _g < arr.length ))
			{
				//line 137 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				java.lang.String s = arr.__get(_g);
				//line 137 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				 ++ _g;
				//line 138 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				if (haxe.lang.Runtime.valEq(s, v)) 
				{
					//line 139 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					 ++ i;
				}
				
			}
			
		}
		
		//line 142 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		return i;
	}
	
	
	public static int selectIndex(haxe.root.Array<java.lang.Object> chain)
	{
		//line 146 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		haxe.root.Array<java.lang.Object> totals = new haxe.root.Array<java.lang.Object>();
		//line 147 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		double accumulator = ((double) (0) );
		//line 149 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		{
			//line 149 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			int _g = 0;
			//line 149 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			while (( _g < chain.length ))
			{
				//line 149 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				double weight = ((double) (haxe.lang.Runtime.toDouble(chain.__get(_g))) );
				//line 149 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				 ++ _g;
				//line 150 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				accumulator += weight;
				//line 151 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				totals.push(accumulator);
			}
			
		}
		
		//line 154 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		double rand = ( java.lang.Math.random() * accumulator );
		//line 155 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		{
			//line 155 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			int _g1 = 0;
			//line 155 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			int _g2 = totals.length;
			//line 155 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			while (( _g1 < _g2 ))
			{
				//line 155 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				int i = _g1++;
				//line 156 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				if (( rand < ((double) (haxe.lang.Runtime.toDouble(totals.__get(i))) ) )) 
				{
					//line 157 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					return i;
				}
				
			}
			
		}
		
		//line 161 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		return 0;
	}
	
	
	public int order;
	
	public double prior;
	
	public haxe.root.Array<java.lang.String> alphabet;
	
	public haxe.ds.StringMap<haxe.root.Array<java.lang.String>> observations;
	
	public haxe.ds.StringMap<haxe.root.Array<java.lang.Object>> chains;
	
	public java.lang.String generate(java.lang.String context)
	{
		//line 66 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		if ( ! ((((boolean) (( context != null )) ))) ) 
		{
			//line 66 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: context != null");
		}
		
		//line 67 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		haxe.root.Array<java.lang.Object> chain = ((haxe.root.Array<java.lang.Object>) (this.chains.get(context)) );
		//line 68 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		if (( chain == null )) 
		{
			//line 69 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			return null;
		}
		else
		{
			//line 71 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			if ( ! ((((boolean) (( chain.length > 0 )) ))) ) 
			{
				//line 71 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				throw haxe.lang.HaxeException.wrap("FAIL: chain.length > 0");
			}
			
			//line 72 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			return this.alphabet.__get(markov.namegen.Model.selectIndex(chain));
		}
		
	}
	
	
	public void retrain(haxe.root.Array<java.lang.String> data)
	{
		//line 81 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		if ( ! ((((boolean) (( data != null )) ))) ) 
		{
			//line 81 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: data != null");
		}
		
		//line 82 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		this.train(data);
		//line 83 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		this.buildChains();
	}
	
	
	public void train(haxe.root.Array<java.lang.String> data)
	{
		//line 91 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		while (( data.length != 0 ))
		{
			//line 92 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			java.lang.String d = haxe.lang.Runtime.toString(data.pop());
			//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			int times = this.order;
			//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			if ( ! (((boolean) (true) )) ) 
			{
				//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				throw haxe.lang.HaxeException.wrap("FAIL: str != null");
			}
			
			//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			if ( ! ((((boolean) (( times >= 1 )) ))) ) 
			{
				//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				throw haxe.lang.HaxeException.wrap("FAIL: times >= 1");
			}
			
			//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			java.lang.String output = "";
			//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			{
				//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				int _g1 = 0;
				//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				int _g = times;
				//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				while (( _g1 < _g ))
				{
					//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					int i = _g1++;
					//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					output += "#";
				}
				
			}
			
			//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			d = ( ( output + d ) + "#" );
			//line 94 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			{
				//line 94 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				int _g11 = 0;
				//line 94 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				int _g2 = ((int) (( ((int) (d.length()) ) - ((int) (this.order) ) )) );
				//line 94 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				while (( _g11 < _g2 ))
				{
					//line 94 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					int i1 = _g11++;
					//line 95 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					java.lang.String key = haxe.lang.StringExt.substring(d, i1, ((int) (( ((int) (i1) ) + ((int) (this.order) ) )) ));
					//line 97 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					haxe.root.Array<java.lang.String> value = ((haxe.root.Array<java.lang.String>) (this.observations.get(key)) );
					//line 98 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (( value == null )) 
					{
						//line 99 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						value = new haxe.root.Array<java.lang.String>();
						//line 100 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						this.observations.set(key, value);
					}
					
					//line 102 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					value.push(haxe.lang.StringExt.charAt(d, ((int) (( ((int) (i1) ) + ((int) (this.order) ) )) )));
				}
				
			}
			
		}
		
	}
	
	
	public void buildChains()
	{
		//line 114 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		this.chains = new haxe.ds.StringMap<haxe.root.Array<java.lang.Object>>();
		//line 116 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		{
			//line 116 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			java.lang.Object context = this.observations.keys();
			//line 116 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			while (haxe.lang.Runtime.toBool(haxe.lang.Runtime.callField(context, "hasNext", null)))
			{
				//line 116 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				java.lang.String context1 = haxe.lang.Runtime.toString(haxe.lang.Runtime.callField(context, "next", null));
				//line 117 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				int _g = 0;
				//line 117 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				haxe.root.Array<java.lang.String> _g1 = this.alphabet;
				//line 117 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				while (( _g < _g1.length ))
				{
					//line 117 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					java.lang.String prediction = _g1.__get(_g);
					//line 117 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					 ++ _g;
					//line 118 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					haxe.root.Array<java.lang.Object> value = ((haxe.root.Array<java.lang.Object>) (this.chains.get(context1)) );
					//line 119 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (( value == null )) 
					{
						//line 120 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						value = new haxe.root.Array<java.lang.Object>();
						//line 121 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						this.chains.set(context1, value);
					}
					
					//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					double tmp = this.prior;
					//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					haxe.root.Array<java.lang.String> arr = ((haxe.root.Array<java.lang.String>) (this.observations.get(context1)) );
					//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					int tmp1 = 0;
					//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (( arr == null )) 
					{
						//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						tmp1 = 0;
					}
					else
					{
						//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						int i = 0;
						//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						{
							//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
							int _g2 = 0;
							//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
							while (( _g2 < arr.length ))
							{
								//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
								java.lang.String s = arr.__get(_g2);
								//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
								 ++ _g2;
								//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
								if (haxe.lang.Runtime.valEq(s, prediction)) 
								{
									//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
									 ++ i;
								}
								
							}
							
						}
						
						//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						tmp1 = i;
					}
					
					//line 123 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					value.push(( tmp + tmp1 ));
				}
				
			}
			
		}
		
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		{
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			boolean __temp_executeDef1 = true;
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			switch (field.hashCode())
			{
				case 106934986:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("prior")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						this.prior = ((double) (value) );
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return value;
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case 106006350:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("order")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						this.order = ((int) (value) );
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return value;
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
			}
			
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			if (__temp_executeDef1) 
			{
				//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		{
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			boolean __temp_executeDef1 = true;
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			switch (field.hashCode())
			{
				case -1361641006:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("chains")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						this.chains = ((haxe.ds.StringMap<haxe.root.Array<java.lang.Object>>) (value) );
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return value;
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case 106006350:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("order")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						this.order = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return value;
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case -502256185:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("observations")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						this.observations = ((haxe.ds.StringMap<haxe.root.Array<java.lang.String>>) (value) );
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return value;
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case 106934986:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("prior")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						this.prior = ((double) (haxe.lang.Runtime.toDouble(value)) );
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return value;
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case 1920525939:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("alphabet")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						this.alphabet = ((haxe.root.Array<java.lang.String>) (value) );
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return value;
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
			}
			
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			if (__temp_executeDef1) 
			{
				//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		{
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			boolean __temp_executeDef1 = true;
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			switch (field.hashCode())
			{
				case 1784195552:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("buildChains")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "buildChains")) );
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case 106006350:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("order")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return this.order;
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case 110621192:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("train")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "train")) );
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case 106934986:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("prior")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return this.prior;
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case 1098369973:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("retrain")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "retrain")) );
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case 1920525939:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("alphabet")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return this.alphabet;
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case 1810371957:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("generate")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "generate")) );
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case -502256185:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("observations")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return this.observations;
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case -1361641006:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("chains")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return this.chains;
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
			}
			
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			if (__temp_executeDef1) 
			{
				//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		{
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			boolean __temp_executeDef1 = true;
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			switch (field.hashCode())
			{
				case 106934986:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("prior")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return this.prior;
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case 106006350:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("order")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return ((double) (this.order) );
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
			}
			
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			if (__temp_executeDef1) 
			{
				//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		{
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			boolean __temp_executeDef1 = true;
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			switch (field.hashCode())
			{
				case 1784195552:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("buildChains")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						this.buildChains();
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case 1810371957:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("generate")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						return this.generate(haxe.lang.Runtime.toString(dynargs.__get(0)));
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case 110621192:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("train")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						this.train(((haxe.root.Array<java.lang.String>) (dynargs.__get(0)) ));
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
				case 1098369973:
				{
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					if (field.equals("retrain")) 
					{
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						__temp_executeDef1 = false;
						//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
						this.retrain(((haxe.root.Array<java.lang.String>) (dynargs.__get(0)) ));
					}
					
					//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
					break;
				}
				
				
			}
			
			//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
			if (__temp_executeDef1) 
			{
				//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		baseArr.push("chains");
		//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		baseArr.push("observations");
		//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		baseArr.push("alphabet");
		//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		baseArr.push("prior");
		//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		baseArr.push("order");
		//line 10 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/namegen/Model.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


