// Generated by Haxe 3.4.2
package markov.util._ArraySet;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public final class ArraySet_Impl_
{
	public static <T> haxe.root.Array<T> create(haxe.root.Array<T> array)
	{
		//line 16 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		if (( array == null )) 
		{
			//line 17 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
			haxe.root.Array<T> this1 = new haxe.root.Array<T>(( (T[]) (new java.lang.Object[] {}) ));
			//line 17 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
			return ((haxe.root.Array<T>) (this1) );
		}
		
		//line 19 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		return ((haxe.root.Array<T>) (markov.util._ArraySet.ArraySet_Impl_.toSet(((haxe.root.Array<T>) (array) ))) );
	}
	
	
	public static <T> haxe.root.Array<T> intersection(haxe.root.Array<T> this1, haxe.root.Array<T> set)
	{
		//line 29 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		haxe.root.Array<T> result = new haxe.root.Array<T>(( (T[]) (new java.lang.Object[] {}) ));
		//line 30 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		{
			//line 30 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
			int _g = 0;
			//line 30 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
			while (( _g < this1.length ))
			{
				//line 30 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
				T element = this1.__get(_g);
				//line 30 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
				 ++ _g;
				//line 31 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
				if (((boolean) (markov.util._ArraySet.ArraySet_Impl_.contains(((haxe.root.Array<T>) (set) ), ((T) (element) ))) )) 
				{
					//line 32 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
					result.push(element);
				}
				
			}
			
		}
		
		//line 35 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		haxe.root.Array<T> this2 = result;
		//line 35 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		return ((haxe.root.Array<T>) (this2) );
	}
	
	
	public static <T> haxe.root.Array<T> union(haxe.root.Array<T> this1, haxe.root.Array<T> set)
	{
		//line 45 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		return ((haxe.root.Array<T>) (markov.util._ArraySet.ArraySet_Impl_.toSet(((haxe.root.Array<T>) (this1.concat(((haxe.root.Array<T>) (markov.util._ArraySet.ArraySet_Impl_.toArray(((haxe.root.Array<T>) (set) ))) ))) ))) );
	}
	
	
	public static <T> haxe.root.Array<T> unionArray(haxe.root.Array<T> this1, haxe.root.Array<T> array)
	{
		//line 55 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		return ((haxe.root.Array<T>) (markov.util._ArraySet.ArraySet_Impl_.toSet(((haxe.root.Array<T>) (this1.concat(array)) ))) );
	}
	
	
	public static <T> haxe.root.Array<T> difference(haxe.root.Array<T> this1, haxe.root.Array<T> set)
	{
		//line 65 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		haxe.root.Array<T> this2 = ((haxe.root.Array<T>) (this1) ).copy();
		//line 65 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		haxe.root.Array<T> result = ((haxe.root.Array<T>) (this2) );
		//line 66 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		{
			//line 66 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
			java.lang.Object element = ((java.lang.Object) (new _Array.ArrayIterator<T>(((haxe.root.Array<T>) (set) ))) );
			//line 66 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
			while (haxe.lang.Runtime.toBool(haxe.lang.Runtime.callField(element, "hasNext", null)))
			{
				//line 66 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
				T element1 = ((T) (haxe.lang.Runtime.callField(element, "next", null)) );
				//line 67 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
				result.remove(element1);
			}
			
		}
		
		//line 69 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		haxe.root.Array<T> this3 = ((haxe.root.Array<T>) (markov.util._ArraySet.ArraySet_Impl_.toArray(((haxe.root.Array<T>) (result) ))) );
		//line 69 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		return ((haxe.root.Array<T>) (this3) );
	}
	
	
	public static <T> boolean add(haxe.root.Array<T> this1, T element)
	{
		//line 79 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		if ( ! ((((boolean) (( ! (( element == null )) )) ))) ) 
		{
			//line 79 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
			throw haxe.lang.HaxeException.wrap("FAIL: element != null");
		}
		
		//line 80 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		if (((boolean) (markov.util._ArraySet.ArraySet_Impl_.contains(((haxe.root.Array<T>) (this1) ), ((T) (element) ))) )) 
		{
			//line 81 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
			return false;
		}
		
		//line 83 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		this1.push(element);
		//line 84 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		return true;
	}
	
	
	public static <T> boolean contains(haxe.root.Array<T> this1, T element)
	{
		//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		{
			//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
			int _g = 0;
			//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
			while (( _g < this1.length ))
			{
				//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
				T i = this1.__get(_g);
				//line 93 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
				 ++ _g;
				//line 94 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
				if (haxe.lang.Runtime.eq(i, element)) 
				{
					//line 95 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
					return true;
				}
				
			}
			
		}
		
		//line 98 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		return false;
	}
	
	
	public static <T> haxe.root.Array<T> copy(haxe.root.Array<T> this1)
	{
		//line 106 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		haxe.root.Array<T> this2 = this1.copy();
		//line 106 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		return ((haxe.root.Array<T>) (this2) );
	}
	
	
	public static <T> haxe.root.Array<T> slice(haxe.root.Array<T> this1, int position, java.lang.Object end)
	{
		//line 116 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		haxe.root.Array<T> this2 = this1.slice(position, end);
		//line 116 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		return ((haxe.root.Array<T>) (this2) );
	}
	
	
	public static <T> haxe.root.Array<T> splice(haxe.root.Array<T> this1, int position, int length)
	{
		//line 126 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		haxe.root.Array<T> this2 = this1.splice(position, length);
		//line 126 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		return ((haxe.root.Array<T>) (this2) );
	}
	
	
	public static <T> haxe.root.Array<T> toArray(haxe.root.Array<T> this1)
	{
		//line 134 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		return this1.copy();
	}
	
	
	public static <T> haxe.root.Array<T> toSet(haxe.root.Array<T> array)
	{
		//line 143 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		haxe.root.Array<T> this1 = new haxe.root.Array<T>(( (T[]) (new java.lang.Object[] {}) ));
		//line 143 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		haxe.root.Array<T> set = ((haxe.root.Array<T>) (this1) );
		//line 144 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		{
			//line 144 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
			int _g = 0;
			//line 144 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
			while (( _g < array.length ))
			{
				//line 144 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
				T v = array.__get(_g);
				//line 144 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
				 ++ _g;
				//line 145 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
				markov.util._ArraySet.ArraySet_Impl_.add(((haxe.root.Array<T>) (set) ), ((T) (v) ));
			}
			
		}
		
		//line 147 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		return set;
	}
	
	
	public static <T> haxe.root.Array<T> _new(haxe.root.Array<T> array)
	{
		//line 154 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		haxe.root.Array<T> this1 = array;
		//line 154 "/Users/rlodge/code/misc/MarkovNameGenerator/lib/markov/util/ArraySet.hx"
		return ((haxe.root.Array<T>) (this1) );
	}
	
	
}


